### ISSUE TITLE
Application Cache is implemented by Safari and Firefox

### ISSUE THREAD

**Issue by xeenon** [MicrosoftEdge/APICatalogData#2]
The data shows Safari and Firefox implement window.applicationCache, but not implementing the ApplicationCache object and its APIs.

**Comment by molant** [comment]
pinging @arronei in case he hasn't seen it

**Comment by arronei** [comment]
The browsers Firefox and Safari do not implement the ApplicationCache interface correctly and the API catalog shows that error in their platform. 

Firefox's IDL:
http://mxr.mozilla.org/mozilla-central/source/dom/webidl/Window.webidl#18

Spec definition:
https://html.spec.whatwg.org/multipage/browsers.html#applicationcache
