### ISSUE TITLE
Add the following specs to specifications list

### ISSUE THREAD

**Issue by josephshum** [MicrosoftEdge/APICatalogData#4]
**Specifications**
- [x] compositing-1	https://www.w3.org/TR/compositing-1/
- [x] css-masking-1	http://www.w3.org/TR/css-masking-1/
- [x] cssom-view-1	 http://www.w3.org/TR/cssom-view-1/
- [x] wbauthn	http://w3c.github.io/webauthn/
- [x] file-system	https://dev.w3.org/2009/dap/file-system/file-writer.html 
- [x] filter-effects-1	
- [x] motion-1	http://www.w3.org/TR/motion-1/
- [x] navigatorcores	
- [x] speech-api	https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html 
- [x] web-bluetooth	
- [x] webdatabase	
- [x] webmessaging	
- [x] web-nfc	
- [x] webstorage	

**Also the following**
- [x] Add url	https://w3c.github.io/webappsec-credential-management/ 
- [x] Add url	https://dev.w3.org/2009/dap/file-system/file-writer.html

**Comment by arronei** [comment]
Added all URLs to the WebIDL Collector
