### ISSUE TITLE
Significantly decreasing number of API support by Firefox

### ISSUE THREAD

**Issue by dynamis** [MicrosoftEdge/APICatalogData#8]
When I see the result last year, Firefox have supported 10,871 APIs but currently 10,225 APIs.
I believe Firefox is not deprecating so many APIs during this period.

Can someone check if current API check for Firefox is correct (or explain why this happen)?
Most large change within this period for Firefox is introducing Stylo (new style engine for Firefox Quantum) but not sure if it's the cause of this or not.

**Comment by molant** [comment]
@arronei is the best person to answer this question.

**Comment by arronei** [comment]
There was actually a bug in our collection logic that was adding members that weren't part of the platform and this was occurring on many types. This bug was fixed the numbers reduced for all platforms. You can see Microsoft Edge's numbers dropped as well.

**Comment by dynamis** [comment]
Thanks for clarification!
